### ISSUE TITLE
Templ & Emmett HTML Completion

### ISSUE THREAD

**Issue by ytsruh** [makifdb/zed-templ#3]
Just wondering if its possible to add this level of support? Like in the templ docs:
https://templ.guide/commands-and-tools/ide-support#emmet-html-completion

I know Emmet is a seperate extension but it appears to not play nicely with the templ extension, persumably becuase it doesn't recognise it as a html file.

Any ideas? Happy to work on this if anybody knows its possible/viable

**Comment by pluja** [comment]
+1 for this, it would be great. I have tried to add this to my `settings.json`:

```
"languages": {
    "Templ": {
      "language_servers": ["emmet-language-server", "templ", "go"]
    }
  }
```

But it seems it is not working, so maybe there's something else needed

**Comment by diegoalzate** [comment]
Might be related but I would +1 with tailwind support which might not be as simple.

seems like there was a solution for astro that might be a good starting point for this:
https://github.com/zed-industries/zed/pull/12741

**Comment by mrg0lden** [comment]
not only emmet but also general HTML support, currently features like auto-closing tags don't work
